######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 22 16:02:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ball.h car.h main.h physicsengine.h vector.h
SOURCES += ball.cpp car.cpp main.cpp physicsengine.cpp vector.cpp
